"""Format and write the Weekly Intelligence Report to disk."""


from datetime import datetime
from pathlib import Path
from typing import Any


def generate_report(
    result: dict[str, Any],
    reports_dir: Path,
    persona_id: str,
) -> Path:
    """Write the synthesized report content to a timestamped Markdown file.

    Returns the path to the generated report file.
    """
    reports_dir = Path(reports_dir)
    reports_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{persona_id}_intelligence_report_{timestamp}.md"
    report_path = reports_dir / filename

    report_content = result.get("report_content", "")

    disclaimer = (
        "\n> *Insights are inferred patterns from your portable data. "
        "Treat them as hypotheses to examine — not diagnoses.*\n"
    )
    report_content = report_content.replace(
        "### EXECUTIVE SUMMARY\n",
        f"### EXECUTIVE SUMMARY\n{disclaimer}",
        1,
    )

    # Add generation metadata footer
    footer = (
        "\n\n---\n"
        f"*Generated by MORPHD Personal Intelligence*  \n"
        f"*Timestamp: {datetime.now().isoformat()}*  \n"
        f"*Persona: {persona_id}*  \n"
        f"*Pipeline: analyze_domains → detect_patterns → synthesize_report*  \n"
        f"*Model: Claude Opus 4.6 / claude-opus-4-6 (Anthropic)*\n"
    )

    report_path.write_text(report_content + footer, encoding="utf-8")
    return report_path
